name: First workflow

on: 
  push:    

jobs:
  hello-job:
    env:
      APP_NAME: CarDealership application
      USERNAME: Noor
      DATE_TODAY: date
      STAGE: dev
    runs-on: ubuntu-latest
    steps:    
      - name: Greetings
        run: echo 'Assalamwalaikum'
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - name: list files
        run: ls
      - name: info
        run: | 
          echo "$USERNAME" 
          echo $(date) 
          echo "$STAGE"          
      - name: Set DB_Password
        env: 
          DB_PASS: ${{secrets.DB_PASSWORD}}
        run: echo "DB Password is set"
