name: First workflow

on: 
  push:    

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:    
      - name: Greetings
        run: echo 'Assalamwalaikum'
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - name: list files
        run: ls
      - name: info
        run: | 
          echo "Noor" $(whoami)
          date
