name: First workflow

on: 
  push:

jobs:
  hello-job:
    runs-on:
      ubuntu-latest
    steps:
      - name: Greetings
        run: echo 'Assalamwalaikum'
      - name: Name of the user
        run: echo "Noor"
      - name: Date
        run: date
